---
title: "Data Preparation Pipeline"
author: "Erik Westlund"
date: "2025-01-13"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: show
    html_document:
      keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(DT)
library(kableExtra)
library(purrr)
library(readr)
library(readxl)
library(rlang)
library(stringr)
library(tidyr)

```

```{r ingest_data, echo=FALSE, message=FALSE}

raw_data <- readRDS("data/FSCI_2024.rds")
targets <- readxl::read_xlsx("data/Codebook Dec 2024.xlsx", sheet = "Indicators and Target Value")
target_year <- 2030

# Contains functions for data preparation
source("functions.R")

```

# Countries

```{r country_summary, echo=FALSE, message=FALSE}
country_indicator_summary <- get_country_indicator_summary(raw_data)
```

## Summary

```{r country_counts, echo=FALSE, message=FALSE}
country_indicator_summary |> 
  summarize(
    n_countries = n(),
    n_regions = n_distinct(region),
    n_income_groups = n_distinct(income_group),
  ) |>
  kable()

```

## Indicators Per Year

The below table shows the number of non-missing indicators a country has in each year.
<br><br>
```{r country_indicators, echo=FALSE, message=FALSE}
DT::datatable(country_indicator_summary, rownames = FALSE, options = list(pageLength = 20, scrollX = TRUE))
```

# Regions

## Summary

```{r region_summary, echo=FALSE, message=FALSE}
region_summary <- get_region_summary(raw_data)

region_summary |> kable()
```

# Income Groups

## Summary

```{r income_group_summary, echo=FALSE, message=FALSE}
income_group_summary <- get_income_group_summary(raw_data)
income_group_summary |> kable()
```

# Indicators

```{r indicator_summary, echo=FALSE, message=FALSE}
indicator_summary <- get_indicator_summary(raw_data)
```

## Summary

```{r indicator_summary_table, echo=FALSE, message=FALSE}

indicator_summary |> 
  summarize(
    n_indicators = n(),
    first_year = min(first_year),
    latest_year = max(latest_year),
    total_years = latest_year - first_year + 1
  ) |>
  kable()

```

## Indicators 

```{r indicator_table, echo=FALSE, message=FALSE}

DT::datatable(indicator_summary, rownames = FALSE, options = list(pageLength = 60, scrollX = TRUE))

```