---
title: "Scratch"
author: "Erik Westlund"
date: "2025-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)

data <- readr::read_csv("data/FSCI_2024.csv")

```

```{r 20pct, echo=TRUE}


# summarize value if year==maxyear, detail
# centile value if maxyear==year, centile(90 85 80)
# egen c20 = pctile(value) if maxyear==year, p(80)
# label variable c20 "Milestone Value"

indicators <- data |> select(indicator) |> distinct() |> pull()

years <- data |> select(year) |> distinct() |> pull()
missing_value_pct <- 100 * (data |> filter(value != "") |> pull(value) |> length() ) / nrow(data)

# Example (could be in loop to generate data)
# Many empty values upon first look
analysis_year <- max(data$year) 

for(i in 1:length(indicators)) {
  indicator <- indicators[i]
  indicator_data <- data %>%
    filter(
      year == analysis_year,
      indicator == indicator
    )
  
  total <- nrow(indicator_data)
  not_empty <- nrow(indicator_data |> filter(value != ""))
  
  print(paste(indicator, total, not_empty, 100 * not_empty / total))
}

analysis_indicator <- indicators[2]

indicator_data <- data %>%
  filter(
    year == maxyear,
    indicator == analysis_indicator
  ) 

indicator_data |> pull(value)

vals <- indicator_data |> pull(value)

quintiles <- quantile(indicator_data$value, seq(0, 1, 0.2))

```